### ISSUE TITLE
server issue

### ISSUE THREAD

**Issue by vondele** [official-stockfish/fishtest#1764]
Looks like 4f8f721b51aa439ecf3003dc3d32ca95820694d6 causes an issue 
First Error in the logs 
```
Aug 28 07:54:35 tests.stockfishchess.org pserve[17947]: Request_task: refresh queue
Aug 28 07:55:36 tests.stockfishchess.org pserve[17947]: Request_task: refresh queue
Aug 28 07:56:38 tests.stockfishchess.org pserve[17947]: Request_task: refresh queue
Aug 28 07:56:44 tests.stockfishchess.org pserve[17947]: Update_task: task 64eb6806e4c98d23e7ae65ad/6 is not active
Aug 28 07:57:40 tests.stockfishchess.org pserve[17947]: Request_task: refresh queue
Aug 28 07:58:58 tests.stockfishchess.org pserve[17947]: Request_task: refresh queue
Aug 28 07:59:59 tests.stockfishchess.org pserve[17947]: Request_task: refresh queue
Aug 28 08:01:04 tests.stockfishchess.org pserve[17947]: Request_task: refresh queue
Aug 28 08:02:11 tests.stockfishchess.org pserve[17947]: Request_task: refresh queue
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]: 2023-08-28 08:02:48,659 ERROR [waitress][waitress-2] Exception while serving /api/update_task
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]: Traceback (most recent call last):
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]:   File "/home/fishtest/fishtest/server/env/lib/python3.11/site-packages/pyramid/tweens.py", line 13, in _error_handler
Aug 28 07:58:58 tests.stockfishchess.org pserve[17947]: Request_task: refresh queue
Aug 28 07:59:59 tests.stockfishchess.org pserve[17947]: Request_task: refresh queue
Aug 28 08:01:04 tests.stockfishchess.org pserve[17947]: Request_task: refresh queue
Aug 28 08:02:11 tests.stockfishchess.org pserve[17947]: Request_task: refresh queue
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]: 2023-08-28 08:02:48,659 ERROR [waitress][waitress-2] Exception while serving /api/update_task
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]: Traceback (most recent call last):
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]:   File "/home/fishtest/fishtest/server/env/lib/python3.11/site-packages/pyramid/tweens.py", line 13, in _error_handler
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]:     response = request.invoke_exception_view(exc_info)
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]:   File "/home/fishtest/fishtest/server/env/lib/python3.11/site-packages/pyramid/view.py", line 786, in invoke_exception_view
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]:     raise HTTPNotFound
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]: pyramid.httpexceptions.HTTPNotFound: The resource could not be found.
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]: During handling of the above exception, another exception occurred:
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]: Traceback (most recent call last):
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]:   File "/home/fishtest/fishtest/server/env/lib/python3.11/site-packages/waitress/channel.py", line 428, in service
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]:     task.service()
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]:   File "/home/fishtest/fishtest/server/env/lib/python3.11/site-packages/waitress/task.py", line 168, in service
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]:     self.execute()
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]:   File "/home/fishtest/fishtest/server/env/lib/python3.11/site-packages/waitress/task.py", line 434, in execute
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]:     app_iter = self.channel.server.application(environ, start_response)
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]:   File "/home/fishtest/fishtest/server/env/lib/python3.11/site-packages/waitress/proxy_headers.py", line 64, in translate_proxy_headers
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]:     return app(environ, start_response)
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]:   File "/home/fishtest/fishtest/server/env/lib/python3.11/site-packages/pyramid/router.py", line 270, in __call__
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]:     response = self.execution_policy(environ, self)
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]:   File "/home/fishtest/fishtest/server/env/lib/python3.11/site-packages/pyramid/router.py", line 276, in default_execution_policy
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]:     return router.invoke_request(request)
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]:   File "/home/fishtest/fishtest/server/env/lib/python3.11/site-packages/pyramid/router.py", line 245, in invoke_request
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]:     response = handle_request(request)
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]:                ^^^^^^^^^^^^^^^^^^^^^^^
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]:   File "/home/fishtest/fishtest/server/env/lib/python3.11/site-packages/pyramid/tweens.py", line 43, in excview_tween
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]:     response = _error_handler(request, exc)
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]:   File "/home/fishtest/fishtest/server/env/lib/python3.11/site-packages/pyramid/tweens.py", line 17, in _error_handler
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]:     reraise(*exc_info)
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]:   File "/home/fishtest/fishtest/server/env/lib/python3.11/site-packages/pyramid/util.py", line 733, in reraise
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]:     raise value
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]:   File "/home/fishtest/fishtest/server/env/lib/python3.11/site-packages/pyramid/tweens.py", line 41, in excview_tween
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]:     response = handler(request)
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]:                ^^^^^^^^^^^^^^^^
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]:   File "/home/fishtest/fishtest/server/env/lib/python3.11/site-packages/pyramid/router.py", line 143, in handle_request
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]:     response = _call_view(
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]:                ^^^^^^^^^^^
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]:   File "/home/fishtest/fishtest/server/env/lib/python3.11/site-packages/pyramid/view.py", line 674, in _call_view
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]:     response = view_callable(context, request)
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]:   File "/home/fishtest/fishtest/server/env/lib/python3.11/site-packages/pyramid/viewderivers.py", line 427, in rendered_view
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]:     result = view(context, request)
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]:              ^^^^^^^^^^^^^^^^^^^^^^
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]:   File "/home/fishtest/fishtest/server/env/lib/python3.11/site-packages/pyramid/viewderivers.py", line 113, in _class_requestonly_view
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]:     response = getattr(inst, attr)()
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]:                ^^^^^^^^^^^^^^^^^^^^^
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]:   File "/home/fishtest/fishtest/server/fishtest/api.py", line 457, in update_task
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]:     result = self.request.rundb.update_task(
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]:   File "/home/fishtest/fishtest/server/fishtest/rundb.py", line 1081, in update_task
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]:     lock = self.active_run_lock(str(run_id))
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]:   File "/home/fishtest/fishtest/server/fishtest/rundb.py", line 997, in active_run_lock
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]:     self.active_runs = dict(
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]:                        ^^^^^
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]:   File "/home/fishtest/fishtest/server/fishtest/rundb.py", line 1000, in <genexpr>
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]:     if v["time"].replace(tzinfo=timezone.utc) >= old
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]:        ^^^^^^^^^^^^^^^^^
Aug 28 08:02:48 tests.stockfishchess.org pserve[17947]: AttributeError: 'float' object has no attribute 'replace'
```

**Comment by ppigazzini** [comment]
Already fixed on PROD, I'm writing the PR
